<a href="https://colab.research.google.com/github/lwaked01/CursoIA/blob/main/EDA_Apuntes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

*EDA analisis exploratorio*

**Ejemplos**

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
!plp list

/bin/bash: line 1: plp: command not found

https//pandas.pydata.org/Pandas_Cheat_Sheet.pdf

In [13]:
df = pd.read_csv("https://raw.githubusercontent.com/adiacla/bigdata/refs/heads/master/vivienda_clasif.csv")

In [ ]:
df.head (10)

   Habitaciones  Area_parqeo  Area_total  Valor_Miles  Clasificacion
0             4         4.98         153       504000              2
1             4         9.14         178       453600              2
2             5         4.03         178       728700              3
3             4         2.94         187       701400              3
4             5         5.33         187       760200              2
5             4         5.21         187       602700              3
6             4        12.43         152       480900              2
7             4        19.15         152       569100              3
8             3        29.93         152       346500              1
9             4        17.10         152       396900              2

from matplotlib import pyplot as plt
_df_0['Habitaciones'].plot(kind='hist', bins=20, title='Habitaciones')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_1['Area_parqeo'].plot(kind='hist', bins=20, title='Area_parqeo')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_2['Area_total'].plot(kind='hist', bins=20, title='Area_total')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_3['Valor_Miles'].plot(kind='hist', bins=20, title='Valor_Miles')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_4.plot(kind='scatter', x='Habitaciones', y='Area_parqeo', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_5.plot(kind='scatter', x='Area_parqeo', y='Area_total', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_6.plot(kind='scatter', x='Area_total', y='Valor_Miles', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_7.plot(kind='scatter', x='Valor_Miles', y='Clasificacion', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_8['Habitaciones'].plot(kind='line', figsize=(8, 4), title='Habitaciones')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_9['Area_parqeo'].plot(kind='line', figsize=(8, 4), title='Area_parqeo')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_10['Area_total'].plot(kind='line', figsize=(8, 4), title='Area_total')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_11['Valor_Miles'].plot(kind='line', figsize=(8, 4), title='Valor_Miles')
plt.gca().spines[['top', 'right']].set_visible(False)

In [16]:
df.tail

<bound method NDFrame.tail of      Habitaciones  Area_parqeo  Area_total  Valor_Miles  Clasificacion
0               4         4.98         153       504000              2
1               4         9.14         178       453600              2
2               5         4.03         178       728700              3
3               4         2.94         187       701400              3
4               5         5.33         187       760200              2
..            ...          ...         ...          ...            ...
484             4         9.67         210       470400              2
485             4         9.08         210       432600              2
486             4         5.64         210       501900              2
487             4         6.48         210       462000              2
488             4         7.88         210       249900              1

[489 rows x 5 columns]>

In [15]:
df

     Habitaciones  Area_parqeo  Area_total  Valor_Miles  Clasificacion
0               4         4.98         153       504000              2
1               4         9.14         178       453600              2
2               5         4.03         178       728700              3
3               4         2.94         187       701400              3
4               5         5.33         187       760200              2
..            ...          ...         ...          ...            ...
484             4         9.67         210       470400              2
485             4         9.08         210       432600              2
486             4         5.64         210       501900              2
487             4         6.48         210       462000              2
488             4         7.88         210       249900              1

[489 rows x 5 columns]